### ISSUE TITLE
Change dashboards to respond to new deadline variable

### ISSUE THREAD

**Issue by parthshahva** [provostprovost/tyto#59]

**Comment by parthshahva** [comment]
Tables of students in each classroom now responds with a different background color for assignments not completed with deadline passed, a color for assignments completed on time with low level score, a color for assignments completed on time with a high level score, and a color for assignments not completed but still on time.

**Comment by provostprovost** [comment]
Working in branch student-deadlines

**Comment by provostprovost** [comment]
Due dates are displayed in student dashboard and assignments are sorted by due date. Didn't see a reason to add a sort button so assignments are sorted by default.
