### ISSUE TITLE
search bar is only responding to one filter

### ISSUE THREAD

**Issue by parthshahva** [provostprovost/tyto#60]

**Comment by provostprovost** [comment]
The search bar should also be able to handle lowercase student names. 'Benny' works but 'benny' does not.

**Comment by parthshahva** [comment]
search bar is not responding to either filter now...

**Comment by parthshahva** [comment]
search bar responds to lowercase student names, but I cannot get the second filter working for students that have been turning in homework late.  I have gone back to the one option filter for now
